sudo: true

services:
  - docker

branches:
  only:
  - master

language: go

go: 1.10.x

env:
  - TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall,e2egwtype"

before_script:
  - make -C test
  - docker ps

script:
  - make test -C test
