sudo: true

services:
  - docker

branches:
  only:
  - master

language: go

go: 1.10.x

before_script:
  - make -C test
  - docker ps

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall,e2egwtype" || make test -C test TEST_VARS="NOLOOP=1 TEST_PATTERNS=sall"'
